#!/usr/bin/env python3
"""
JooJoo Land 로컬 개발 서버.

1) .env 읽어서 VWORLD_API_KEY 추출
2) config.js 자동 생성 (gitignored)
3) /api/vworld/* 프록시 (VWorld API CORS 우회)
4) http.server 시작 (기본 포트 8000)

사용: python serve.py [port]
"""
import http.server
import os
import socketserver
import sys
import urllib.parse
import urllib.request
from pathlib import Path

# Windows 콘솔 한글 출력 (cp949 → utf-8)
try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).parent
ENV_FILE = ROOT / ".env"
CONFIG_FILE = ROOT / "config.js"

VWORLD_HOSTS = {
    "address": "https://api.vworld.kr/req/address",
    "data":    "https://api.vworld.kr/req/data",
    "wms":     "https://api.vworld.kr/req/wms",
    "wmts":    "https://api.vworld.kr/req/wmts",
}


def load_env(path: Path) -> dict:
    """간단한 .env 파서 (KEY=VALUE, # 주석, 따옴표 제거)."""
    env = {}
    if not path.exists():
        return env
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        v = v.strip().strip('"').strip("'")
        env[k.strip()] = v
    return env


def write_config(env: dict):
    """config.js 생성 — 브라우저에서 window.VWORLD_KEY / window.CESIUM_ION_TOKEN 로 접근."""
    def esc(s):
        return (s or "").replace("\\", "\\\\").replace("'", "\\'")

    key = env.get("VWORLD_API_KEY", "")
    ion = env.get("CESIUM_ION_TOKEN", "")
    content = (
        "// AUTO-GENERATED by serve.py — 직접 수정 금지 (gitignored)\n"
        f"window.VWORLD_KEY = '{esc(key)}';\n"
        f"window.CESIUM_ION_TOKEN = '{esc(ion)}';\n"
    )
    CONFIG_FILE.write_text(content, encoding="utf-8")
    if key and key != "PASTE_YOUR_KEY_HERE":
        print(f"[serve.py] config.js 생성 (VWorld: {key[:8]}...{key[-4:]}, Cesium Ion: {'있음' if ion else '없음(평면지구)'})")
    else:
        print("[serve.py] .env 에 VWORLD_API_KEY 없음 — 브라우저 모달로 입력 필요")


class Handler(http.server.SimpleHTTPRequestHandler):
    """정적 파일 + /api/vworld/* 프록시 + 캐시 무효화."""

    def do_GET(self):
        if self.path.startswith("/api/vworld/"):
            self.handle_vworld_proxy()
            return
        super().do_GET()

    def handle_vworld_proxy(self):
        """/api/vworld/<endpoint>?query → https://api.vworld.kr/req/<endpoint>?query"""
        parsed = urllib.parse.urlparse(self.path)
        # /api/vworld/address?... → endpoint = "address"
        parts = parsed.path.split("/", 3)
        if len(parts) < 4:
            self.send_error(400, "Invalid proxy path")
            return
        endpoint = parts[3]
        upstream = VWORLD_HOSTS.get(endpoint)
        if not upstream:
            self.send_error(404, f"Unknown endpoint: {endpoint}")
            return

        url = f"{upstream}?{parsed.query}"
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "JooJooLand/1.0"})
            with urllib.request.urlopen(req, timeout=15) as resp:
                body = resp.read()
                content_type = resp.headers.get("Content-Type", "application/json; charset=utf-8")
            self.send_response(resp.status)
            self.send_header("Content-Type", content_type)
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Cache-Control", "public, max-age=60")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        except urllib.error.HTTPError as e:
            body = e.read()
            self.send_response(e.code)
            self.send_header("Content-Type", e.headers.get("Content-Type", "text/plain"))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        except Exception as e:
            self.send_error(502, f"Proxy error: {e}")

    def end_headers(self):
        # /api/* 는 위에서 이미 end_headers 호출됨
        if not self.path.startswith("/api/"):
            self.send_header("Cache-Control", "public, max-age=0, must-revalidate")
            self.send_header("Pragma", "no-cache")
        super().end_headers()

    def log_message(self, format, *args):
        sys.stderr.write(f"[{self.log_date_time_string()}] {format % args}\n")


def main():
    os.chdir(ROOT)
    env = load_env(ENV_FILE)
    write_config(env)

    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8000
    # ThreadingTCPServer 로 프록시 동시 호출 지원
    class ThreadedServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
        allow_reuse_address = True
        daemon_threads = True

    with ThreadedServer(("", port), Handler) as httpd:
        print(f"[serve.py] http://localhost:{port} 서빙 중 (Ctrl+C 종료)")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\n[serve.py] 종료")


if __name__ == "__main__":
    main()
